# roles/install_files/tasks/main.yml

---

- name: ติดตั้งไฟล์ RPM ทั้งหมด
  yum:
    name: "{{ package_dir }}/{{ item.file }}"
    state: present
  loop: "{{ packages }}"
  when: item.type == 'rpm'

# —————— ปรับตรงนี้ ——————

- name: แตกไฟล์ TGZ ทุกตัวไปไว้ที่ /opt
  unarchive:
    src: "{{ package_dir }}/{{ item.file }}"
    dest: /opt
    remote_src: yes
    # สร้างเงื่อนไขให้ข้ามถ้าแตกไปแล้ว
    creates: "/opt/{{ item.file | regex_replace('\\.tgz$', '') }}"
  loop: "{{ packages }}"
  when: item.type == 'tgz'

- name: สร้าง symlink ให้เรียกใช้ไบนารีจาก TGZ
  file:
    src: "/opt/{{ item.file | regex_replace('\\.tgz$', '') }}/bin/{{ item.name }}"
    dest: "/usr/local/bin/{{ item.name }}"
    state: link
    force: yes
  loop: "{{ packages }}"
  when: item.type == 'tgz'

# ————————————————————

- name: เก็บคำสั่งตรวจสอบเวอร์ชันแต่ละแพ็กเกจ
  vars:
    version_cmd: >-
      {% if item.type == 'rpm' %}
      rpm -q {{ item.name }} --queryformat '%{VERSION}-%{RELEASE}\n'
      {% else %}
      {{ item.name }} --version
      {% endif %}
  shell: "{{ version_cmd }}"
  register: version_results
  loop: "{{ packages }}"

- name: แสดงผลสรุปเวอร์ชันอย่างสวยงาม
  debug:
    msg: "✅ {{ packages[loop.index0].name }}: {{ item.stdout }}"
  loop: "{{ version_results.results }}"
  loop_control:
    label: "{{ packages[loop.index0].name }}"
