---
- name: Check installed version
  command: "{{ package_item.version_check_cmd }}"
  register: version_output
  changed_when: false
  failed_when: false
  ignore_errors: true

- name: Report version information
  debug:
    msg: "Version check for {{ package_item.name }}: {{ version_output.stdout | default('Command failed') }}"