---
- name: Sort packages by order
  set_fact:
    sorted_packages: "{{ packages | sort(attribute='order') }}"
  when: 
    - packages | selectattr('order', 'defined') | list | length > 0

- name: Use original package list if no order defined
  set_fact:
    sorted_packages: "{{ packages }}"
  when:
    - packages | selectattr('order', 'defined') | list | length == 0

- name: Display packages installation order
  debug:
    msg: "Installation order: {{ sorted_packages | map(attribute='name') | list }}"

- name: Create temp download directory if needed
  file:
    path: "{{ temp_download_dir }}"
    state: directory
    mode: '0755'
  when: sorted_packages | selectattr('url', 'defined') | list | length > 0

- name: Process RPM packages in order
  include_tasks: process_rpm.yml
  vars:
    package_item: "{{ item }}"
  with_items: "{{ sorted_packages }}"
  when: item.type | default('rpm') == 'rpm'

- name: Process TGZ packages
  include_tasks: process_tgz.yml
  vars:
    package_item: "{{ item }}"
  with_items: "{{ sorted_packages }}"
  when: item.type | default('rpm') == 'tgz'