---
# Flexible RPM Package Processing Playbook

- name: Find matching RPM package
  block:
    - name: Search for matching package file
      find:
        paths: "{{ package_item.source_dir | default(packages_dir, true) }}"
        patterns: "{{ package_item.name }}*.rpm"
        use_regex: no
      register: matching_packages

    - name: Set package source path
      set_fact:
        package_source_path: "{{ matching_packages.files[0].path }}"
      when: matching_packages.files | length > 0

    - name: Fail if no matching package found
      fail:
        msg: |
          No matching RPM package found for {{ package_item.name }}
          Search directory: {{ package_item.source_dir | default(packages_dir, true) }}
          Available files:
          {{ matching_packages.files | map(attribute='path') | list | to_nice_yaml }}
      when: matching_packages.files | length == 0

- name: Debug selected package
  debug:
    msg: "Selected package path: {{ package_source_path }}"

- name: Check if package is already installed
  command: rpm -q {{ package_item.name }}
  register: rpm_check
  failed_when: false
  changed_when: false

- name: Import GPG key if provided
  rpm_key:
    key: "{{ package_item.gpg_key }}"
    state: present
  when: package_item.gpg_key is defined

- name: Install RPM package
  yum:
    name: "{{ package_source_path }}"
    state: present
    disable_gpg_check: "{{ package_item.disable_gpg_check | default(disable_gpg_check | default(false)) }}"
  register: rpm_install
  when: rpm_check.rc != 0
  
- name: Detailed package information gathering
  block:
    - name: Retrieve package details
      shell: |
        echo "===== PACKAGE INFORMATION ====="
        rpm -qi {{ package_item.name }} | grep -E 'Name|Version|Release|Description'
        echo ""
        echo "===== INSTALLED FILES ====="
        rpm -ql {{ package_item.name }} | head -10
        total_files=$(rpm -ql {{ package_item.name }} | wc -l)
        if [ $total_files -gt 10 ]; then
          echo "... and $(( $total_files - 10 )) more files"
        fi
      register: package_info
      changed_when: false
      when: rpm_check.rc != 0

    - name: Display package information
      debug:
        var: package_info.stdout_lines
      when: rpm_check.rc != 0 and package_info is defined

    - name: Version check
      block:
        - name: Run version check command
          shell: "{{ package_item.version_check_cmd }}"
          register: version_check
          changed_when: false
          failed_when: false
        
        - name: Display version
          debug:
            msg: "Version check for {{ package_item.name }}: {{ version_check.stdout }}"
          when: version_check.rc == 0
      when: package_item.version_check_cmd is defined

  when: show_detailed_output | bool