---
- name: Create temp directory if needed
  file:
    path: "{{ temp_download_dir }}"
    state: directory
    mode: '0755'
  when: temp_download_dir is defined

- name: Verify RPM files exist
  stat:
    path: "/tmp/aws-rds/libicu-76.1-4.fc42.i686.rpm"
  register: rpm_file_check

- name: Show file existence result
  debug:
    msg: "File exists: {{ rpm_file_check.stat.exists }}"

- name: Run ls command to check directory contents
  shell: "ls -la /tmp/aws-rds/"
  register: ls_output
  changed_when: false

- name: Show directory contents
  debug:
    msg: "{{ ls_output.stdout_lines }}"

- name: Copy RPM file to ensure correct permissions
  copy:
    src: "/tmp/aws-rds/libicu-76.1-4.fc42.i686.rpm"
    dest: "/tmp/libicu-76.1-4.fc42.i686.rpm"
    remote_src: yes
    mode: '0644'
  ignore_errors: true

- name: Process each package
  include_tasks: process_package.yml
  loop: "{{ packages }}"
  loop_control:
    loop_var: package_item

- name: Generate final installation report
  template:
    src: report.j2
    dest: "{{ output_file }}"
  when: show_detailed_output | bool