---
- name: Ensure dnf-plugins-core is installed on controller
  package:
    name: dnf-plugins-core
    state: present
  delegate_to: localhost
  run_once: true

- name: Ensure download directory exists on controller
  file:
    path: "{{ download_dir }}"
    state: directory
  delegate_to: localhost
  run_once: true

- name: Download PostgreSQL repo RPM
  get_url:
    url: "{{ repo_rpm_url }}"
    dest: "{{ download_dir }}/{{ repo_rpm_url | basename }}"
  delegate_to: localhost
  run_once: true

- name: Download PostgreSQL client RPMs and dependencies
  command: >
    dnf download --resolve --alldeps
    --downloaddir {{ download_dir }}
    {{ item }}
  loop: "{{ client_packages }}"
  delegate_to: localhost
  run_once: true

- name: List downloaded RPM files
  shell: ls -1 {{ download_dir }}
  register: downloaded_files
  delegate_to: localhost
  run_once: true

- name: Show what was downloaded
  debug:
    var: downloaded_files.stdout_lines