---
- name: Ensure dnf-plugins-core is present on download host
  yum:
    name: dnf-plugins-core
    state: present
  become: true

- name: Ensure python3-dnf package is installed for module support
  yum:
    name: python3-dnf
    state: present
  become: true

- name: Create download directory on download host
  file:
    path: "{{ download_dir }}"
    state: directory
    mode: '0755'
  become: true

- name: Download PostgreSQL repo RPM
  get_url:
    url: "{{ repo_rpm_url }}"
    dest: "{{ download_dir }}/{{ repo_rpm_url | basename }}"
  become: true

- name: Download PostgreSQL client RPMs and dependencies
  command: >
    dnf download --resolve --alldeps
    --downloaddir {{ download_dir }}
    {{ item }}
  loop: "{{ client_packages }}"
  become: true

- name: List downloaded RPM files
  command: ls -1 {{ download_dir }}
  register: downloaded_files
  become: true

- name: Display downloaded files
  debug:
    msg: "Downloaded RPMs: {{ downloaded_files.stdout_lines }}"