---
packages:
  - name: mysql-shell
    file: "mysql-shell-8.4.5-1.el9.x86_64.rpm"
    source_dir: "/tmp/aws-rds/"
    type: "rpm"
    disable_gpg_check: true
    version_check_cmd: "mysql-shell --version"
  
  - name: mariadb
    file: "mariadb-connector-odbc-3.2.5-1.el9.x86_64.rpm"
    source_dir: "/tmp/aws-rds/"
    type: "rpm"
    disable_gpg_check: true
    version_check_cmd: "odbcinst -q -d"  
  
  - name: oracle-instantclient-basic
    file: "oracle-instantclient-basic-23.8.0.25.04-1.el9.x86_64.rpm"
    source_dir: "/tmp/aws-rds/"
    type: "rpm"
    disable_gpg_check: true
    version_check_cmd: "ls -la /usr/lib/oracle/23.7.0.25.01/client64/lib" 

  - name: my-mongosh
    file: "mongosh-2.5.0-linux-x64-openssl3.tgz"
    source_dir: "/tmp/aws-rds/"
    type: "tgz"
    extract_path: "/opt/my-app"
    version_check_cmd: "/opt/my-app/mongosh-2.5.0-linux-x64/bin/mongosh --version"

show_detailed_output: true
output_file: "/tmp/installation_report.txt"

temp_download_dir: "/tmp/downloads"


disable_gpg_check: false
