# playbooks/roles/repo_installer/tasks/main.yml
---
- name: Create output directory if needed
  file:
    path: "{{ output_file | dirname }}"
    state: directory
    mode: '0755'
  when: output_file is defined
  become: yes

- name: Initialize output file
  copy:
    content: "Repository Installation Report - {{ ansible_date_time.date }} {{ ansible_date_time.time }}\n=============================================\n\n"
    dest: "{{ output_file }}"
    mode: '0644'
    force: yes
  when: output_file is defined
  become: yes

- name: Install and configure MSSQL Tools
  include_tasks: mssql_tools.yml
  when: install_mssql_tools | bool

- name: Install and configure PostgreSQL client
  include_tasks: postgresql.yml
  when: install_postgresql | bool

- name: Append final summary to output file
  blockinfile:
    path: "{{ output_file }}"
    marker: "# {mark} INSTALLATION SUMMARY"
    block: |
      ===== INSTALLATION SUMMARY =====
      
      MSSQL Tools: {{ 'INSTALLED' if (install_mssql_tools | bool) else 'SKIPPED' }}
      PostgreSQL: {{ 'INSTALLED' if (install_postgresql | bool) else 'SKIPPED' }}
      
      ===== END OF REPORT =====
  when: output_file is defined
  become: yes

- name: Show final summary
  debug:
    msg: |
      ===== INSTALLATION SUMMARY =====
      
      MSSQL Tools: {{ 'INSTALLED' if (install_mssql_tools | bool) else 'SKIPPED' }}
      PostgreSQL: {{ 'INSTALLED' if (install_postgresql | bool) else 'SKIPPED' }}
      
      Detailed report saved to: {{ output_file if (output_file is defined) else 'Not requested' }}
      
      ===============================
  when: show_detailed_output | bool