# ---
# # name: Install Server Packages and Repositories
# - name: Install Server Packages and Repositories
#   hosts: all
#   #connection: local
#   become: yes  
#   # vars:
#   #   nexus_files:
#   #     - "mariadb-connector-odbc-3.2.5-1.el9.x86_64.rpm"
#   #     - "mongosh-2.5.0-linux-x64-openssl3.tgz"
#   #     - "mssql-tools-17.10.1.1-1.x86_64.rpm"
#   #     - "oracle-instantclient-basic-23.7.0.25.01-1.el9.x86_64.rpm"
#   #     - "pgdg-redhat-repo-latest.noarch.rpm"
#   #     - "mysql-shell-8.4.5-1.el9.x86_64.rpm"
    
#   #   show_detailed_output: true
#   #   output_file: "/tmp/aws-rds/package_installation_report.txt"
#   #   download_path: "/tmp/aws-rds/"
  
#   tasks:
#   #   # First create the download directory to ensure it exists
#   #   - name: Create destination directory
#   #     ansible.builtin.file:
#   #       path: "{{ download_path }}"
#   #       state: directory
#   #       mode: '0755'
#   #     become: yes

#   #   # Then include the role with fixed variable definitions
#   #   - name: "Nexus : Import role ks.utils.nexus_tasks"
#   #     ansible.builtin.include_role:
#   #       name: ks.utils.nexus_tasks
#   #     vars:
#   #       filename: "{{ item }}"
#   #       nexus_repo_group: "/bay/aws-dbclient"
#   #       nexus_repo: "bay-automation-pub"
#   #       nexus_downloaded_path: "{{ download_path }}"
#   #       action_tasks: ["download_1file"]
#   #     loop: "{{ nexus_files }}"
    
#   #   - name: List files in the download directory
#   #     ansible.builtin.find:
#   #       paths: "{{ download_path }}"
#   #     register: downloaded_files
    
#   #   - name: Display downloaded files
#   #     ansible.builtin.debug:
#   #       msg: "Files in {{ download_path }}: {{ downloaded_files.files | map(attribute='path') | map('basename') | list }}"
    
#   #   - name: Write downloaded files to report
#   #     ansible.builtin.copy:
#   #       content: "Downloaded files in {{ download_path }}:\n{% for file in downloaded_files.files %}{{ file.path }}\n{% endfor %}"
#   #       dest: "/tmp/downloaded_files_report.txt"

#     - name: Using role to install
#       ansible.builtin.import_role:
#         name: package_installer
- name: Install database packages
  hosts: all
  become: true
  roles:
    - postgresql_repo