# roles/sql_server_tools/tasks/install_offline.yml
---
- name: Install packages using rpm directly (sequential installation)
  block:
    - name: Install unixODBC
      command: rpm -Uvh --nodeps /tmp/aws-rds/unixODBC-2.3.11-1.rh.x86_64.rpm
      register: unixodbc_install
      ignore_errors: true
      
    - name: Install unixODBC-devel
      command: rpm -Uvh --nodeps /tmp/aws-rds/unixODBC-devel-2.3.11-1.rh.x86_64.rpm
      register: unixodbc_devel_install
      ignore_errors: true
      when: unixodbc_install is success or 'already installed' in unixodbc_install.stderr
      
    - name: Install msodbcsql18
      command: rpm -Uvh --nodeps /tmp/aws-rds/msodbcsql18-18.4.1.1-1.x86_64.rpm
      register: msodbcsql_install
      ignore_errors: true
      
    - name: Install mssql-tools18
      command: rpm -Uvh --nodeps /tmp/aws-rds/mssql-tools18-18.4.1.1-1.x86_64.rpm
      register: mssql_tools_install
      ignore_errors: true
      
  always:
    - name: Report installation results
      debug:
        msg:
          - "unixODBC status: {{ 'SUCCESS' if unixodbc_install.rc == 0 or 'already installed' in unixodbc_install.stderr|default('') else 'FAILED - ' + unixodbc_install.stderr|default('unknown error') }}"
          - "unixODBC-devel status: {{ 'SUCCESS' if unixodbc_devel_install.rc == 0 or 'already installed' in unixodbc_devel_install.stderr|default('') else 'FAILED - ' + unixodbc_devel_install.stderr|default('unknown error') }}"
          - "msodbcsql18 status: {{ 'SUCCESS' if msodbcsql_install.rc == 0 or 'already installed' in msodbcsql_install.stderr|default('') else 'FAILED - ' + msodbcsql_install.stderr|default('unknown error') }}"
          - "mssql-tools18 status: {{ 'SUCCESS' if mssql_tools_install.rc == 0 or 'already installed' in mssql_tools_install.stderr|default('') else 'FAILED - ' + mssql_tools_install.stderr|default('unknown error') }}"