---
- name: Download and Install AWS RDS Client Packages
  hosts: all
  #connection: local
  become: yes
  
  # roles:
  #   - role: aws_db_client_setup
  #     vars:
  #       download_path: "/tmp/aws-rds"
  #       nexus_files:
  #         - "mariadb-connector-odbc-3.2.5-1.el9.x86_64.rpm"
  #         - "mongosh-2.5.0-linux-x64-openssl3.tgz"
  #         - "mssql-tools-17.10.1.1-1.x86_64.rpm"
  #         - "oracle-instantclient-basic-23.7.0.25.01-1.el9.x86_64.rpm"
  #         - "pgdg-redhat-repo-latest.noarch.rpm"
    
    - role: package_installer
      vars:
        temp_download_dir: "/tmp/aws-rds"
        disable_gpg_check: true
        report_file: "/tmp/aws-rds/installation_report.txt"
        packages:
          - name: "mariadb-connector-odbc"
            file: "mariadb-connector-odbc-3.2.5-1.el9.x86_64.rpm"
            type: "rpm"
            source_dir: "/tmp/aws-rds"
            version_command: "odbcinst -q -d -n MariaDB"
          
          - name: "mongosh"
            file: "mongosh-2.5.0-linux-x64-openssl3.tgz"
            type: "tgz"
            source_dir: "/tmp/aws-rds"
            extract_path: "/opt/mongodb"
            creates: "/opt/mongodb/bin/mongosh"
            version_command: "/opt/mongodb/bin/mongosh --version"
          
          - name: "mssql-tools"
            file: "mssql-tools-17.10.1.1-1.x86_64.rpm"
            type: "rpm"
            source_dir: "/tmp/aws-rds"
            disable_gpg_check: true
          
          - name: "oracle-instantclient-basic"
            file: "oracle-instantclient-basic-23.7.0.25.01-1.el9.x86_64.rpm"
            type: "rpm"
            source_dir: "/tmp/aws-rds"
          
          - name: "pgdg-redhat-repo"
            file: "pgdg-redhat-repo-latest.noarch.rpm"
            type: "rpm"
            source_dir: "/tmp/aws-rds"
