# Main tasks file for aws_db_client_setup
---
# First create the download directory to ensure it exists
- name: Create destination directory
  ansible.builtin.file:
    path: "{{ download_path }}"
    state: directory
    mode: '0755'
  become: yes

# Include the download tasks
- name: Include download tasks
  ansible.builtin.include_tasks: download.yml

# List files in the download directory
- name: List files in the download directory
  ansible.builtin.find:
    paths: "{{ download_path }}"
  register: downloaded_files

# Show output if detailed output is enabled
- name: Display downloaded files
  ansible.builtin.debug:
    msg: "Files in {{ download_path }}: {{ downloaded_files.files | map(attribute='path') | map('basename') | list }}"
  when: show_detailed_output | bool

# Write report file
- name: Write downloaded files to report
  ansible.builtin.copy:
    content: "Downloaded files in {{ download_path }}:\n{% for file in downloaded_files.files %}{{ file.path }}\n{% endfor %}"
    dest: "{{ output_file }}"