---
# roles/db_packages/defaults/main.yml

# Whether to clean up the temporary directory after installation
cleanup_temp: true

# Whether to ignore errors during package installation
ignore_package_errors: false

# Target hosts (can be overridden in the playbook command)
target_hosts: all

# Source directory where packages are located (can be overridden)
package_source_dir: "/tmp/aws-rds"

# Whether to check package dependencies before installing
check_dependencies: true

# Whether to use force install (rpm -ivh --nodeps) for RPM packages
use_force_install: true

# Whether to skip the standard install method and go straight to force install
use_force_install_only: true