# Main tasks file for package_installer
---
- name: Create temporary download directory
  ansible.builtin.file:
    path: "{{ temp_download_dir }}"
    state: directory
    mode: '0755'
  become: yes


- name: Process all packages
  include_tasks: "process_{{ package_item.type }}.yml"
  vars:
    package_item: "{{ item }}"
  loop: "{{ packages }}"
  loop_control:
    label: "{{ item.name }} ({{ item.file }})"


- name: Create installation report
  ansible.builtin.copy:
    content: |
      Package Installation Report
      ===============================
      Date: {{ ansible_date_time.date }}
      Time: {{ ansible_date_time.time }}
      
      Packages Installed:
      {% for item in packages %}
      - {{ item.name }} ({{ item.file }})
      {% endfor %}
    dest: "{{ report_file }}"
  when: packages|length > 0